
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SharpTL compiler (https://github.com/Taggersoft/SharpTL).
//     Generated at 11/19/2014 11:28:27
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable 1591
// ReSharper disable UnusedMember.Global
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable ClassNeverInstantiated.Global
// ReSharper disable InconsistentNaming
namespace SharpMTProto.Schema
{
    using System;
    using System.Collections.Generic;
    using System.Threading.Tasks;

    [Flags]
    public enum MessageSendingFlags
    {
        None = 0,
        Encrypted = 1,
        ContentRelated = 1 << 1,
        EncryptedAndContentRelated = Encrypted | ContentRelated
    }

    /// <summary>
    ///     Interface for remote procedure calls.
    /// </summary>
    public interface IRemoteProcedureCaller
    {
        /// <summary>
        ///     Sends query without waiting for any result.
        /// </summary>
        /// <param name="requestBody">Request body.</param>
        Task SendAsync(object requestBody);

        /// <summary>
        ///     Sends RPC and wait for result response asynchronously.
        /// </summary>
        /// <typeparam name="TResponse">Type of a result response.</typeparam>
        /// <param name="requestBody">Request body.</param>
        /// <returns>Response.</returns>
        Task<TResponse> RpcAsync<TResponse>(object requestBody);

        /// <summary>
        ///     Sets flags for message sendings.
        /// </summary>
        /// <param name="flags">Dictionary: (Type of request body)-(message sending flags).</param>
        void SetMessageSendingFlags(Dictionary<Type, MessageSendingFlags> flags);
    }

    public partial class MTProtoAsyncMethods : IMTProtoAsyncMethods
    {
        private readonly IRemoteProcedureCaller _remoteProcedureCaller;

        public MTProtoAsyncMethods(IRemoteProcedureCaller remoteProcedureCaller)
        {
            _remoteProcedureCaller = remoteProcedureCaller;
            SetupRemoteProcedureCaller(remoteProcedureCaller);
        }

        partial void SetupRemoteProcedureCaller(IRemoteProcedureCaller remoteProcedureCaller);

        public Task<IResPQ> ReqPqAsync(ReqPqArgs args)
        {
            return _remoteProcedureCaller.RpcAsync<IResPQ>(args);
        }

        public Task<IServerDHParams> ReqDHParamsAsync(ReqDHParamsArgs args)
        {
            return _remoteProcedureCaller.RpcAsync<IServerDHParams>(args);
        }

        public Task<ISetClientDHParamsAnswer> SetClientDHParamsAsync(SetClientDHParamsArgs args)
        {
            return _remoteProcedureCaller.RpcAsync<ISetClientDHParamsAnswer>(args);
        }

        public Task<IRpcDropAnswer> RpcDropAnswerAsync(RpcDropAnswerArgs args)
        {
            return _remoteProcedureCaller.RpcAsync<IRpcDropAnswer>(args);
        }

        public Task<IFutureSalts> GetFutureSaltsAsync(GetFutureSaltsArgs args)
        {
            return _remoteProcedureCaller.RpcAsync<IFutureSalts>(args);
        }

        public Task<IPong> PingAsync(PingArgs args)
        {
            return _remoteProcedureCaller.RpcAsync<IPong>(args);
        }

        public Task<IPong> PingDelayDisconnectAsync(PingDelayDisconnectArgs args)
        {
            return _remoteProcedureCaller.RpcAsync<IPong>(args);
        }

        public Task<IDestroySessionRes> DestroySessionAsync(DestroySessionArgs args)
        {
            return _remoteProcedureCaller.RpcAsync<IDestroySessionRes>(args);
        }

        public Task HttpWaitAsync(HttpWaitArgs args)
        {
            return _remoteProcedureCaller.SendAsync(args);
        }

    }
}
#pragma warning restore 1591
